version: '3.8'

networks:
  recruitment-net1:
  recruitment-net2:

volumes:
  recruitment-vol:

services:

  recruitment-app:
    image: nimeshsv814/recruitment-app:v1.1.1
    container_name: recruitment-app
    networks:
      - recruitment-net1
    ports:
      - "85:3000"
    environment:
      - MONGO_URI=mongodb://rootuser:root123@10.0.1.129:27017/hr_system?authSource=rootuser
    
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - recruitment-net2
    volumes:
      - recruitment-vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017:27017"
